CREATE TABLE [dbo].[projects] (
    [nID]                       INT             IDENTITY (1000, 1) NOT NULL,
    [dtCreateDate]              DATETIME2 (7)   CONSTRAINT [DF_projects_dtCreateDate] DEFAULT (getdate()) NULL,
    [nUsersID]                  INT             NULL,
    [bGlobalUsers]              BIT             NULL,
    [cName]                     NVARCHAR (50)   NULL,
    [cDesc]                     NVARCHAR (MAX)  NULL,
    [bDeleted]                  BIT             NULL,
    [cNote1]                    NVARCHAR (MAX)  NULL,
    [cNote2]                    NVARCHAR (MAX)  NULL,
    [nClientsID]                INT             NULL,
    [dtDateDue]                 DATETIME2 (7)   NULL,
    [nDemandTotal]              DECIMAL (18, 6) NULL,
    [nCityID]                   INT             NULL,
    [nChosenInsolation]         DECIMAL (18, 6) NULL,
    [cChosenTilt]               NVARCHAR (100)  NULL,
    [nMPPTFactor]               DECIMAL (18, 6) NULL,
    [nBatteryEfficiency]        DECIMAL (18, 6) NULL,
    [nInverterDerate]           DECIMAL (18, 6) NULL,
    [nColdestAirTempC]          DECIMAL (8, 2)  NULL,
    [nMDoD]                     DECIMAL (8, 2)  NULL,
    [nDaysAutonomy]             DECIMAL (8, 2)  NULL,
    [nVoltage]                  DECIMAL (8, 2)  NULL,
    [nControllerEfficiency]     DECIMAL (8, 2)  NULL,
    [nTDR]                      DECIMAL (8, 2)  NULL,
    [nChosenPV]                 DECIMAL (18, 6) NULL,
    [nChosenBattery]            DECIMAL (18, 6) NULL,
    [dtSummaryStartDate]        DATETIME2 (7)   NULL,
    [dtSummaryEndDate]          DATETIME2 (7)   NULL,
    [nCityIDDemand]             INT             NULL,
    [nManualLat]                DECIMAL (18, 6) NULL,
    [nManualLong]               DECIMAL (18, 6) NULL,
    [bUserSpecifiedCoordinates] BIT             NULL,
    [nReflectance]              DECIMAL (18, 6) NULL,
    [nDemandQty]                DECIMAL (18, 6) CONSTRAINT [DF_projects_nDemandQty] DEFAULT ((1)) NULL,
    [nMetricsResolution]        INT             NULL,
    [nMetricsHour]              INT             NULL,
    [nGMTPlusMinus]             DECIMAL (18, 6) NULL,
    [nChosenAzimuth]            DECIMAL (18, 6) NULL,
    [nCustomTilt]               DECIMAL (18, 6) NULL,
    [nCO2g_perkWhCoal]          DECIMAL (18, 6) NULL,
    [nCO2g_perkWhPV]            DECIMAL (18, 6) NULL,
    [bDaylightTime]             BIT             NULL,
    [dtDaylightFirst]           DATETIME2 (7)   NULL,
    [dtDaylightLast]            DATETIME2 (7)   NULL,
    [cTMYFile]                  NVARCHAR (MAX)  NULL,
    CONSTRAINT [PK_projects] PRIMARY KEY CLUSTERED ([nID] ASC)
);

